export const LOGGER_ENTITY_NAME = 'logger'

export const LOG_LEVEL = {
  DEBUG: 'debug',
  ERROR: 'error',
  INFO: 'info',
  WARN: 'warn',
}

export const API_LOGGER_COLORS = {
  bgBlack: 'bgBlack',
  bgBlackBright: 'bgBlackBright',
  bgBlue: 'bgBlue',
  bgBlueBright: 'bgBlueBright',
  bgCyan: 'bgCyan',
  bgCyanBright: 'bgCyanBright',
  bgGreen: 'bgGreen',
  bgGreenBright: 'bgGreenBright',
  bgMagenta: 'bgMagenta',
  bgMagentaBright: 'bgMagentaBright',
  bgRed: 'bgRed',
  bgRedBright: 'bgRedBright',
  bgWhite: 'bgWhite',
  bgWhiteBright: 'bgWhiteBright',
  bgYellow: 'bgYellow',
  bgYellowBright: 'bgYellowBright',
  black: 'black',
  blackBright: 'blackBright',
  blue: 'blue',
  blueBright: 'blueBright',
  cyan: 'cyan',
  cyanBright: 'cyanBright',
  gray: 'gray',
  green: 'green',
  greenBright: 'greenBright',
  grey: 'grey',
  magenta: 'magenta',
  magentaBright: 'magentaBright',
  red: 'red',
  redBright: 'redBright',
  white: 'white',
  whiteBright: 'whiteBright',
  yellow: 'yellow',
  yellowBright: 'yellowBright',
}
