export const DEVICES_ENTITY_NAME = 'devices'
export const DEVICES_POSTGRES_DB_NAME = 'devices'
export const FACIAL_AUTH_STATE = {
  CHALLENGE: 'CHALLENGE',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
  SUCCESS: 'SUCCESS',
}
