export enum IconNames {
  ACCESSIBLITY = 'ACCESSIBLITY',
  ADMIN_PANEL_SETTINGS = 'ADMIN_PANEL_SETTINGS',
  ARTICLE = 'ARTICLE',
  CHECK = 'CHECK',
  CHECKBOX = 'CHECKBOX',
  CHECKBOX_OUTLINED_BLANK = 'CHECKBOX_OUTLINED_BLANK',
  DASHBOARD = 'DASHBOARD',
  FLAG = 'FLAG',
  HEALTHZ = 'HEALTHZ',
  HELP_OUTLINE = 'HELP_OUTLINE',
  HOME = 'HOME',
  INFO_OUTLINE = 'INFO_OUTLINE',
  MAIL_OUTLINE = 'MAIL_OUTLINE',
  MANAGE_ACCOUNTS = 'MANAGE_ACCOUNTS',
  MENU_OPEN = 'MENU_OPEN',
  PEOPLE = 'PEOPLE',
  PEOPLE_OUTLINE = 'PEOPLE_OUTLINE',
  STATS = 'STATS',
  SUPPORT = 'SUPPORT',
  SUPPORT_AGENT = 'SUPPORT_AGENT',
}

export const getIconNameSelect = (): IconNames[] => {
  const keys = Object.keys(IconNames)
  return keys as IconNames[]
}
