/**
 * Error Shared Constants
 *
 * Centralized error codes used across API and frontend.
 * Codes are grouped by domain with specific ranges.
 *
 * Code Ranges:
 * - 100-199: Authentication & Authorization
 * - 200-299: Media/Upload
 * - 300-399: User Management
 * - 400-499: Email
 * - 500-599: Phone
 * - 600-699: Notifications
 * - 700-799: Feature Flags
 * - 900-999: Generic/System
 */

// biome-ignore assist/source/useSortedKeys: intentional key order
export const ERROR_CODES = {
  // Authentication (100-199)
  AUTH_FAILED: '100',
  AUTH_INVALID_CREDENTIALS: '101',
  AUTH_OTP_EXPIRED: '102',
  AUTH_OTP_INVALID: '103',
  AUTH_SESSION_EXPIRED: '104',
  AUTH_TOKEN_INVALID: '105',
  AUTH_UNAUTHORIZED: '106',
  AUTH_INCOMPLETE_BIOMETRIC: '107',
  AUTH_INVALID_BIOMETRIC: '108',
  AUTH_SIGNUP_FAILED: '109',
  AUTH_SIGNUP_BAD_PHONE_TYPE: '110',

  // Media/Upload (200-299)
  MEDIA_FILE_COUNT_EXCEEDED: '200',
  MEDIA_FILE_SIZE_EXCEEDED: '201',
  MEDIA_INVALID_TYPE: '202',
  MEDIA_UPLOAD_FAILED: '203',

  // User Management (300-399)
  USER_ACCOUNT_NOT_SECURED: '306',
  USER_ALREADY_EXISTS: '300',
  USER_CREATE_FAILED: '301',
  USER_NOT_FOUND: '302',
  USER_PROFANE_USERNAMES_NOT_ALLOWED: '304',
  USER_UPDATE_FAILED: '303',
  USER_USERNAME_UNAVAILABLE: '305',

  // Email (400-499)
  EMAIL_ALREADY_EXISTS: '400',
  EMAIL_DELETE_FAILED: '401',
  EMAIL_INVALID: '402',
  EMAIL_NOT_FOUND: '403',
  EMAIL_SEND_FAILED: '404',
  EMAIL_VERIFICATION_FAILED: '405',

  // Phone (500-599)
  PHONE_ALREADY_EXISTS: '500',
  PHONE_DELETE_FAILED: '501',
  PHONE_INVALID: '502',
  PHONE_NOT_FOUND: '503',
  PHONE_VERIFICATION_FAILED: '504',

  // Notifications (600-699)
  NOTIFICATION_CREATE_FAILED: '600',
  NOTIFICATION_MISSING_PARAMS: '601',
  NOTIFICATION_MISSING_USER_ID: '602',
  NOTIFICATION_SERVER_ERROR: '603',

  // Feature Flags (700-799)
  FEATURE_FLAG_CREATE_FAILED: '700',
  FEATURE_FLAG_DISABLED: '701',
  FEATURE_FLAG_EVALUATION_ERROR: '702',
  FEATURE_FLAG_NOT_FOUND: '703',
  FEATURE_FLAG_UPDATE_FAILED: '704',

  // Generic/System (900-999)
  GENERIC_BAD_REQUEST: '900',
  GENERIC_FORBIDDEN: '901',
  GENERIC_NOT_FOUND: '902',
  GENERIC_SERVER_ERROR: '903',
  GENERIC_VALIDATION_FAILED: '904',
} as const

/**
 * Maps error codes to i18n string keys.
 * Frontend uses this to display localized error messages.
 */
export const ERROR_CODE_TO_I18N_KEY: Record<string, string> = {
  [ERROR_CODES.AUTH_FAILED]: 'AUTH_FAILED',
  [ERROR_CODES.AUTH_INCOMPLETE_BIOMETRIC]: 'AUTH_INCOMPLETE_BIOMETRIC',
  [ERROR_CODES.AUTH_INVALID_BIOMETRIC]: 'AUTH_INVALID_BIOMETRIC',
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 'AUTH_INVALID_CREDENTIALS',
  [ERROR_CODES.AUTH_OTP_EXPIRED]: 'AUTH_OTP_EXPIRED',
  [ERROR_CODES.AUTH_OTP_INVALID]: 'AUTH_OTP_INVALID',
  [ERROR_CODES.AUTH_SESSION_EXPIRED]: 'AUTH_SESSION_EXPIRED',
  [ERROR_CODES.AUTH_SIGNUP_BAD_PHONE_TYPE]: 'AUTH_SIGNUP_BAD_PHONE_TYPE',
  [ERROR_CODES.AUTH_SIGNUP_FAILED]: 'AUTH_SIGNUP_FAILED',
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 'AUTH_TOKEN_INVALID',
  [ERROR_CODES.AUTH_UNAUTHORIZED]: 'AUTH_UNAUTHORIZED',
  [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 'EMAIL_ALREADY_EXISTS',
  [ERROR_CODES.EMAIL_DELETE_FAILED]: 'EMAIL_DELETE_FAILED',
  [ERROR_CODES.EMAIL_INVALID]: 'EMAIL_INVALID',
  [ERROR_CODES.EMAIL_NOT_FOUND]: 'EMAIL_NOT_FOUND',
  [ERROR_CODES.EMAIL_SEND_FAILED]: 'EMAIL_SEND_FAILED',
  [ERROR_CODES.EMAIL_VERIFICATION_FAILED]: 'EMAIL_VERIFICATION_FAILED',
  [ERROR_CODES.FEATURE_FLAG_CREATE_FAILED]: 'FEATURE_FLAG_CREATE_FAILED',
  [ERROR_CODES.FEATURE_FLAG_DISABLED]: 'FEATURE_FLAG_DISABLED',
  [ERROR_CODES.FEATURE_FLAG_EVALUATION_ERROR]: 'FEATURE_FLAG_EVALUATION_ERROR',
  [ERROR_CODES.FEATURE_FLAG_NOT_FOUND]: 'FEATURE_FLAG_NOT_FOUND',
  [ERROR_CODES.FEATURE_FLAG_UPDATE_FAILED]: 'FEATURE_FLAG_UPDATE_FAILED',
  [ERROR_CODES.GENERIC_BAD_REQUEST]: 'GENERIC_BAD_REQUEST',
  [ERROR_CODES.GENERIC_FORBIDDEN]: 'GENERIC_FORBIDDEN',
  [ERROR_CODES.GENERIC_NOT_FOUND]: 'GENERIC_NOT_FOUND',
  [ERROR_CODES.GENERIC_SERVER_ERROR]: 'GENERIC_SERVER_ERROR',
  [ERROR_CODES.GENERIC_VALIDATION_FAILED]: 'GENERIC_VALIDATION_FAILED',
  [ERROR_CODES.MEDIA_FILE_COUNT_EXCEEDED]: 'MEDIA_FILE_COUNT_EXCEEDED',
  [ERROR_CODES.MEDIA_FILE_SIZE_EXCEEDED]: 'MEDIA_FILE_SIZE_EXCEEDED',
  [ERROR_CODES.MEDIA_INVALID_TYPE]: 'MEDIA_INVALID_TYPE',
  [ERROR_CODES.MEDIA_UPLOAD_FAILED]: 'MEDIA_UPLOAD_FAILED',
  [ERROR_CODES.NOTIFICATION_CREATE_FAILED]: 'NOTIFICATION_CREATE_FAILED',
  [ERROR_CODES.NOTIFICATION_MISSING_PARAMS]: 'NOTIFICATION_MISSING_PARAMS',
  [ERROR_CODES.NOTIFICATION_MISSING_USER_ID]: 'NOTIFICATION_MISSING_USER_ID',
  [ERROR_CODES.NOTIFICATION_SERVER_ERROR]: 'NOTIFICATION_SERVER_ERROR',
  [ERROR_CODES.PHONE_ALREADY_EXISTS]: 'PHONE_ALREADY_EXISTS',
  [ERROR_CODES.PHONE_DELETE_FAILED]: 'PHONE_DELETE_FAILED',
  [ERROR_CODES.PHONE_INVALID]: 'PHONE_INVALID',
  [ERROR_CODES.PHONE_NOT_FOUND]: 'PHONE_NOT_FOUND',
  [ERROR_CODES.PHONE_VERIFICATION_FAILED]: 'PHONE_VERIFICATION_FAILED',
  [ERROR_CODES.USER_ACCOUNT_NOT_SECURED]: 'USER_ACCOUNT_NOT_SECURED',
  [ERROR_CODES.USER_ALREADY_EXISTS]: 'USER_ALREADY_EXISTS',
  [ERROR_CODES.USER_CREATE_FAILED]: 'USER_CREATE_FAILED',
  [ERROR_CODES.USER_NOT_FOUND]: 'USER_NOT_FOUND',
  [ERROR_CODES.USER_PROFANE_USERNAMES_NOT_ALLOWED]: 'USER_PROFANE_USERNAMES_NOT_ALLOWED',
  [ERROR_CODES.USER_UPDATE_FAILED]: 'USER_UPDATE_FAILED',
  [ERROR_CODES.USER_USERNAME_UNAVAILABLE]: 'USER_USERNAME_UNAVAILABLE',
}
